### ISSUE TITLE
Test results of training with SD.

### ISSUE THREAD

**Issue by zhanganny** [saidwivedi/TokenHMR#11]
Hello, thanks for your great job! I'm confused why the test results of TokenHMR on SD is not showed in paper? I wonder whether its performance can surpass the other method listed (such as HMR2.0、CLIFF、HybrIK). Have you ever tried to compute the metrics on SD?

Looking forward to your reply!

<img width="752" alt="image" src="https://github.com/user-attachments/assets/955a9a55-d158-482d-b1ed-595a8a3bc11b">

**Comment by saidwivedi** [comment]
TokenHMR enables training methods that use large scale in-the-wild pseudo-GT data with the goal of generalising for difficult poses while not compromising on 3D accuracy. Since SD contains very less in-the-wild pseudo-GT data, we never trained on this train split. However, feel free to train a version with SD data and let us know your findings.

**Comment by saidwivedi** [comment]
Closing the issue now, if you have further questions, feel free to ask.
