### ISSUE TITLE
Camera parameters

### ISSUE THREAD

**Issue by SebastienLinker** [saidwivedi/TokenHMR#9]
Hi,

I was wondering which dataset you used to train the part that estimates the camera matrix? Is there any reason why the model does not estimate the camera location or orientation as well? Would it give a better result in 3D reconstruction?

**Comment by saidwivedi** [comment]
In most HPS methods, we assume weak perspective camera with camera in the center and unit rotation. We only estimate the `[tx, ty, s]` camera parameters (see [here](https://github.com/saidwivedi/TokenHMR/blob/e4c8577d9934432f99d53f44490e7454989b21f7/tokenhmr/lib/models/tokenhmr.py#L166C35-L166C43)). We do this because we do not have ground-truth camera for in-the-wild cases. So, if we have GT camera, we can learn the camera location and orientation which would lead to better 3D reconstruction.
